"""Initial

Revision ID: 217397c601ba
Revises: 
Create Date: 2021-03-24 07:59:32.752905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217397c601ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='type'), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('working_hours', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('courier_id', name=op.f('pk__couriers'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('delivery_hours', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk__orders'))
    )
    op.create_table('assigned_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('assign_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], name=op.f('fk__assigned_orders__courier_id__couriers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk__assigned_orders__order_id__orders')),
    sa.PrimaryKeyConstraint('order_id', 'courier_id', name=op.f('pk__assigned_orders'))
    )
    op.create_table('completed_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('complete_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], name=op.f('fk__completed_orders__courier_id__couriers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk__completed_orders__order_id__orders')),
    sa.PrimaryKeyConstraint('order_id', 'courier_id', name=op.f('pk__completed_orders'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_orders')
    op.drop_table('assigned_orders')
    op.drop_table('orders')
    op.drop_table('couriers')
    # ### end Alembic commands ###
